name = "my-blog"
compatibility_date = "2025-08-29"

# Use the Next.js adapter for Pages
pages_build_output_dir = ".next"

# Environment variables should be configured in Cloudflare Pages dashboard
# Never put API keys in this file as it will be public on GitHub!
